title: IQMR 2025
alt_title: IQMR Navigator
preposition: ''
description: >-
  Institute for Qualitative and Multi-Method Research (IQMR) 2025
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iqmrnavigator.org" # the base hostname & protocol for your site, e.g. https://example.com

#theme: jekyll-theme-conference
remote_theme: "DigitaleGesellschaft/jekyll-theme-conference@v3.6.1"
# Build settings
markdown: kramdown
plugins:
  - jekyll-target-blank
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - vendor
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: en

  # Timezone
  tz: "+02:00"

  # Show theme errors:
  show_errors: False

  # Navigation bar
  navigation:
    logo:
      name: IQMR
      img: 'iqmr-logo-small.png'  # inside /assets/images/
      url: 'https://iqmrnavigator.org'
    breakpoint: md
    links:
      - name: Schedule
        relative_url: /schedule/
      - name: General Information
        relative_url: /information/
        menu:
          - name: Overview
            relative_url: /information
        #  - name: Location
        #    relative_url: /information/location/
        #  - name: Accommodations
        #    relative_url: /information/accommodations/
        #  - name: Travel
       #     relative_url: /information/travel/
        #  - name: Contact
        #    relative_url: /information/contact/
      - name: Participant Information
        relative_url: /participants/
        menu:
          - name: Overview
            relative_url: /participants
          - name: Lodging
            relative_url: /participants/lodging
          - name: Choosing Modules
            relative_url: /participants/choosing-modules
          - name: Module Prerequisites
            relative_url: /participants/module-prerequisites
          - name: Readings and Materials
            relative_url: /participants/readings
          - name: Research Design Instructions
            relative_url: /participants/research-design-instructions
          - name: Research Design Sessions
            relative_url: /participants/research-design-groups
          - name: Syracuse University
            relative_url: /participants/syracuse-university
#          - name: Code of Conduct
 #           relative_url: /participants/code-of-conduct/
  #        - name: FAQ
   #         relative_url: /participants/faq/
      - name: Instructor Information
        relative_url: /instructors/
        menu:
          - name: Overview
            relative_url: /instructors
          - name: Designing and Teaching Your Modules
            relative_url: /instructors/designing-teaching 
          - name: Chairing Research Design Sessions
            relative_url: /instructors/chairing-research-design
          - name: Materials, Technology, and Services
            relative_url: /instructors/materials-services
          - name: Travel and Lodging
            relative_url: /instructors/travel-lodging
          - name: Honorarium Payment, Per Diem, and Travel Reimbursement
            relative_url: /instructors/honoraria-logistics
      - name: Weekend Workshops
        relative_url: /authors-workshop/
        menu:
          - name: Overview
            relative_url: /authors-workshop/
     

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
   # logo:
    #  img: 'iqmr-logo-full.svg'
    links:
      - name: Schedule
        relative_url: /schedule/
      - name: General Info
        relative_url: /information/ 
      - name: Participant Info
        relative_url: /participants/
      - name: Instructor Info
        relative_url: /instructors/
      - name: Weekend Workshops
        relative_url: /authors-workshop/


  # Information boxes
  info_bars:
    - title: Welcome to the IQMR 2025 Weekend Workshops
      color: primary
      text: |
        "Advances in Qualitative and Multi-Methods Research" and the "Emerging Methodologist Workshop" are for invited authors only. IQMR Participants are encouraged to spend the weekend getting to know each other better and enjoying the beautiful central New York region.
  #      ---
#
  #      See the [README](github.com/DigitaleGesellschaft/jekyll-theme-conference/) on the project's GitHub repository for further information on how to configure and adapt it to your needs.
  #  - text: This is just some random content for demonstration purposes.
  #    color: warning
  #    pages_only: true
#
  # Live indications
  live:
    date: 01.01.2020
    timezone: GMT+1
    stop:       240  # in minutes
    streaming:
      enable: true
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  talks:
    # Talk categories
    main_categories:
      - name: Cat A
        color: info
      - name: Cat B
        color: success

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page.  Set `map: false` if you don't want to
    # display it.
    map:
      # Initial map center point
      home_coord: 47.37808, 8.53935
      # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
      # The following do match the Bootstrap design not too badly:
      #   - Thunderforest.Neighbourhood
      #   - Esri.WorldTopoMap
      map_provider: "OpenStreetMap.Mapnik"
      default_zoom: 17


  schedule:
    # URL of schedule page
    url: '/schedule'

    # Time steps in schedule table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
